### ISSUE TITLE
Workaround doesn't work anymore on ubuntu-latest

### ISSUE THREAD

**Issue by satoshiotomakan** [mjp41/workaround8649#3]
Hi @mjp41, thank you for the workaround! Unfortunately, it doesn't work anymore. Do you have any idea on how to fix the errors below?

E: Version '2.35-*' for 'libc6' was not found
E: Version '2.35-*' for 'libc6-dev' was not found
E: Version '12.3.0-*' for 'libstdc++6' was not found
E: Version '12.3.0-*' for 'libgcc-s1' was not found

The reason is that ubuntu-latest is no longer ubuntu-22.04, but ubuntu-24.04: https://github.com/actions/runner-images/issues/10636

**Comment by mjp41** [comment]
It looks like github actions has deployed 24.04 as Ubuntu latest.  When I package this workaround it was 22.04, so I think it is making incorrect assumptions for ubuntu-latest.

**Comment by mjp41** [comment]
Could you please post the full error message you are using, and also confirm you are using the up-to-date hash:

   c8550b715ccdc17f89c8d5c28d7a48eeff9c94a8

Thanks

**Comment by satoshiotomakan** [comment]
@mjp41 https://productionresultssa3.blob.core.windows.net/actions-results/6960e6eb-cafd-45c8-a232-f3ce46796b73/workflow-job-run-ca395085-040a-526b-2ce8-bdc85f692774/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-10-14T12%3A48%3A29Z&sig=uNABTd1FzgMf6gsrEDrJAegArZ74AKjIXFB7mf5g%2BV8%3D&ske=2024-10-14T21%3A31%3A12Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-10-14T09%3A31%3A12Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-08-04&sp=r&spr=https&sr=b&st=2024-10-14T12%3A38%3A24Z&sv=2024-08-04

**Comment by satoshiotomakan** [comment]
@mjp41 looks like the issue https://github.com/actions/runner-images/issues/8659 has been solved by upgrading to ubuntu 24.04 👍

**Comment by mjp41** [comment]
Based on my testing the workaround is no longer required for any versions.

https://github.com/mjp41/workaround8649/actions/runs/11327838480
